#!/usr/bin/env python3
"""Independent, dependency-free reference arithmetic. Never invokes MoonBit."""
import argparse
import hashlib
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]

def tensor(shape, data):
    return {"shape": shape, "dtype": "float32", "data": data}

def linear_reference():
    x = [[1.0, -2.0, 0.5], [0.0, 1.0, -1.0]]
    w = [[0.5, -1.0], [2.0, 0.25], [-0.5, 1.5]]
    b = [0.125, -0.25]
    y = [sum(row[k] * w[k][j] for k in range(3)) + b[j] for row in x for j in range(2)]
    return {"input": tensor([2, 3], sum(x, [])), "weight": tensor([3, 2], sum(w, [])),
            "bias": tensor([1, 2], b), "expected": tensor([2, 2], y)}

def render(name, document):
    compact = json.dumps(document, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
    return f'''// Generated by scripts/generate-references.py; do not hand edit.
///|
pub fn {name}() -> Json raise {{
  let text =
    #|{compact}
  @json.parse(text)
}}
'''

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    documents = {"linear": linear_reference()}
    manifest = {"schema": "json-regress-reference/v1", "generator": "python3 scripts/generate-references.py",
                "source": "Project-authored independent Python scalar arithmetic (Apache-2.0)",
                "randomness": "none", "files": {}}
    outputs = {}
    for name, document in documents.items():
        encoded = json.dumps(document, ensure_ascii=False, indent=2, allow_nan=False) + "\n"
        outputs[f"fixtures/{name}.json"] = encoded
        outputs[f"fixtures/{name}.mbt"] = render(name, document)
        manifest["files"][f"{name}.json"] = hashlib.sha256(encoded.encode()).hexdigest()
    outputs["fixtures/manifest.json"] = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    for relative, content in outputs.items():
        path = root / relative
        if args.check:
            actual = path.read_text() if path.exists() else ""
            if path.suffix == ".mbt":
                actual_json = [line.strip()[2:] for line in actual.splitlines() if line.strip().startswith("#|")]
                wanted_json = [line.strip()[2:] for line in content.splitlines() if line.strip().startswith("#|")]
                matches = actual_json == wanted_json
            else:
                matches = actual == content
            if not matches:
                raise SystemExit(f"Reference drift: {relative}; regenerate and review the mathematical change.")
        else:
            path.write_text(content)
    print(f"{'Verified' if args.check else 'Generated'} {len(documents)} independent reference fixture(s).")

if __name__ == "__main__":
    main()
